from __future__ import annotations

import json
from pathlib import Path
from shutil import copy2


REPO_ROOT = Path(__file__).resolve().parents[1]


DOCUMENTS = [
    {
        "source_number": 1,
        "document_id": "nat_azwa_2025_definitief",
        "title": "Aanvullend Zorg- en Welzijnsakkoord (AZWA) (Definitief)",
        "short_title": "AZWA definitief",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2025-08-31",
        "document_type": "agreement",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/rapporten/2025/08/31/aanvullend-zorg-en-welzijnsakkoord-azwa",
        "status": "current",
        "priority_rank": 1,
        "selected_source_file": "sources/01-aanvullend-zorg-en-welzijnsakkoord-azwa__PDIZA-1087289TK_B_Aanvullend_Zorg-_en_Welzijnsakkoord_AZWA_.pdf",
    },
    {
        "source_number": 2,
        "document_id": "nat_azwa_2025_aanbiedingsbrief",
        "title": "Kamerbrief aanbieding Aanvullend Zorg- en Welzijnsakkoord (AZWA)",
        "short_title": "Kamerbrief aanbieding AZWA",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2025-09-08",
        "document_type": "kamerbrief",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/kamerstukken/2025/09/08/kamerbrief-over-aanbieding-aanvullend-zorg-en-welzijnsakkoord-azwa",
        "status": "reference",
        "priority_rank": 8,
        "selected_source_file": "sources/02-kamerbrief-over-aanbieding-aanvullend-zorg-en-welzijnsakkoord-azwa__PDIZA-1087289TK_A.pdf",
    },
    {
        "source_number": 3,
        "document_id": "nat_azwa_2026_cw31_kamerbrief",
        "title": "Kamerbrief over CW 3.1 kaders voor AZWA onderdelen",
        "short_title": "Kamerbrief CW 3.1 kaders AZWA",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2026-03-10",
        "document_type": "kamerbrief",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/kamerstukken/2026/03/10/kamerbrief-over-cw3-1-kaders-voor-azwa-onderdelen",
        "status": "current",
        "priority_rank": 6,
        "selected_source_file": "sources/03-kamerbrief-over-cw3-1-kaders-voor-azwa-onderdelen__FEZ-1094401_A.pdf",
    },
    {
        "source_number": 4,
        "document_id": "nat_azwa_2026_cw31_kader_d5_d6",
        "title": "CW 3.1 kader basisfunctionaliteiten en basisinfrastructuur D5 en D6",
        "short_title": "CW 3.1 kader D5/D6",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2026-03-10",
        "document_type": "framework",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/publicaties/2026/03/10/cw-3-1-kader-basisfunctionaliteiten-en-basisinfrastructuur-d5-en-d6",
        "status": "current",
        "priority_rank": 3,
        "selected_source_file": "sources/04-cw-3-1-kader-basisfunctionaliteiten-en-basisinfrastructuur-d5-en-d6__FEZ-1094401_C_CW_3.1_kader_Basisfunctionaliteiten_en_basisinfrastructuur-_D5_en_D6.pdf",
    },
    {
        "source_number": 5,
        "document_id": "nat_azwa_2026_voortgang_kamerbrief",
        "title": "Kamerbrief inzake voortgang Integraal Zorgakkoord (IZA) en Aanvullend Zorg- en Welzijnsakkoord (AZWA)",
        "short_title": "Voortgangsbrief IZA/AZWA",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2026-04-09",
        "document_type": "kamerbrief",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/kamerstukken/2026/04/09/kamerbrief-inzake-voortgang-integraal-zorgakkoord-iza-en-aanvullend-zorg-en-welzijnsakkoord-azwa",
        "status": "current",
        "priority_rank": 7,
        "selected_source_file": "sources/05-kamerbrief-inzake-voortgang-integraal-zorgakkoord-iza-en-aanvullend-zorg-en-welzijnsakkoord-azwa__PDIZA-1095964_A.pdf",
    },
    {
        "source_number": 6,
        "document_id": "nat_azwa_2025_onderhandelaarsakkoord",
        "title": "Aanvullend Zorg- en Welzijnsakkoord - onderhandelaarsakkoord",
        "short_title": "AZWA onderhandelaarsakkoord",
        "publisher": "VNG",
        "publication_date": "2025-07-11",
        "document_type": "agreement",
        "jurisdiction_level": "national",
        "source_url": "https://vng.nl/brieven/onderhandelaarsakkoord-aanvullend-zorg-en-welzijnsakkoord-azwa",
        "status": "reference",
        "priority_rank": 2,
        "selected_source_file": "sources/06-onderhandelaarsakkoord-aanvullend-zorg-en-welzijnsakkoord-azwa__PDIZA-1085052_B_Aanvullend_Zorg-_en_Welzijnsakkoord_-_onderhandelaarsakkoord.pdf",
    },
    {
        "source_number": 7,
        "document_id": "nat_vng_azwa_faq_middelen",
        "title": "Welke middelen zijn beschikbaar in het AZWA en hoe worden deze middelen verdeeld?",
        "short_title": "VNG FAQ middelen AZWA",
        "publisher": "VNG",
        "publication_date": None,
        "document_type": "faq",
        "jurisdiction_level": "national",
        "source_url": "https://vng.nl/vragen-en-antwoorden/welke-middelen-zijn-beschikbaar-in-het-azwa-en-hoe-worden-deze-middelen-verdeeld",
        "status": "supporting",
        "priority_rank": 13,
        "selected_source_file": "sources/07-welke-middelen-zijn-beschikbaar-in-het-azwa-en-hoe-worden-deze-middelen-verdeeld.html",
    },
    {
        "source_number": 8,
        "document_id": "nat_vng_azwa_faq_uitvoeringscapaciteit",
        "title": "Is er rekening gehouden met de benodigde uitvoeringscapaciteit van gemeenten bij het AZWA?",
        "short_title": "VNG FAQ uitvoeringscapaciteit AZWA",
        "publisher": "VNG",
        "publication_date": None,
        "document_type": "faq",
        "jurisdiction_level": "national",
        "source_url": "https://vng.nl/vragen-en-antwoorden/is-er-rekening-gehouden-met-de-benodigde-uitvoeringscapaciteit-van-gemeenten-bij-het-azwa",
        "status": "supporting",
        "priority_rank": 14,
        "selected_source_file": "sources/08-is-er-rekening-gehouden-met-de-benodigde-uitvoeringscapaciteit-van-gemeenten-bij-het-azwa.html",
    },
    {
        "source_number": 9,
        "document_id": "nat_iza_2022_integraal_zorgakkoord",
        "title": "Integraal Zorgakkoord: Samen werken aan gezonde zorg",
        "short_title": "IZA 2022",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2022-09-16",
        "document_type": "agreement",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/rapporten/2022/09/16/integraal-zorgakkoord-samen-werken-aan-gezonde-zorg",
        "status": "reference",
        "priority_rank": 9,
        "selected_source_file": "sources/09-integraal-zorgakkoord-samen-werken-aan-gezonde-zorg__integraal-zorg-akkoord.pdf",
    },
    {
        "source_number": 10,
        "document_id": "nat_gala_2023_gezond_en_actief_leven",
        "title": "GALA - Gezond en Actief Leven Akkoord",
        "short_title": "GALA 2023",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2023-01-31",
        "document_type": "agreement",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/rapporten/2023/01/31/gala-gezond-en-actief-leven-akkoord",
        "status": "reference",
        "priority_rank": 10,
        "selected_source_file": "sources/10-gala-gezond-en-actief-leven-akkoord__gala-gezond-en-actief-leven-akkoord.pdf",
    },
    {
        "source_number": 11,
        "document_id": "reg_flevoland_2023_regiobeeld",
        "title": "Regiobeeld Flevoland 2023",
        "short_title": "Regiobeeld Flevoland 2023",
        "publisher": "Flever",
        "publication_date": "2023-07-12",
        "document_type": "regional_report",
        "jurisdiction_level": "regional",
        "source_url": "https://flever.nl/kennisbank/regiobeeld-flevoland-2023/",
        "status": "reference",
        "priority_rank": 12,
        "selected_source_file": "sources/11-regiobeeld-flevoland-2023__Regiobeeld-Flevoland.pdf",
    },
    {
        "source_number": 12,
        "document_id": "reg_flevoland_2023_regioplan_iza",
        "title": "Zorgzaam Flevoland 2023 Regioplan IZA Flevoland",
        "short_title": "Regioplan IZA Flevoland",
        "publisher": "Zorgzaam Flevoland / Flever",
        "publication_date": "2023-12-22",
        "document_type": "regional_plan",
        "jurisdiction_level": "regional",
        "source_url": "https://flever.nl/wp-content/uploads/2024/01/Regioplan_IZA_Flevoland_ZorgzaamFlevoland2023.pdf",
        "status": "reference",
        "priority_rank": 4,
        "selected_source_file": "sources/12-regioplan_iza_flevoland_zorgzaamflevoland2023__Regioplan_IZA_Flevoland_ZorgzaamFlevoland2023.pdf",
    },
    {
        "source_number": 13,
        "document_id": "mun_almere_sociaal_domein_informatiepagina",
        "title": "Informatiepagina Sociaal Domein",
        "short_title": "Sociaal domein informatiepagina",
        "publisher": "Raad van Almere",
        "publication_date": "2026-03-25",
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://raadvanalmere.nl/page/informatiepagina-sociaal-domein",
        "status": "supporting",
        "priority_rank": 17,
        "selected_source_file": "sources/13-informatiepagina-sociaal-domein.html",
    },
    {
        "source_number": 14,
        "document_id": "mun_almere_sociale_staat_gateway",
        "title": "Sociale staat van Almere",
        "short_title": "Sociale staat van Almere gateway",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_gateway_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/sociale-staat-van-almere",
        "status": "supporting",
        "priority_rank": 18,
        "selected_source_file": "sources/14-sociale-staat-van-almere.html",
    },
    {
        "source_number": 15,
        "document_id": "mun_almere_2024_2034_maatschappelijke_agenda",
        "title": "Maatschappelijke agenda 2024-2034",
        "short_title": "Maatschappelijke agenda 2024-2034",
        "publisher": "Raad van Almere",
        "publication_date": "2024-06-10",
        "document_type": "municipal_policy_summary",
        "jurisdiction_level": "municipal",
        "source_url": "https://raadvanalmere.nl/article/maatschappelijke-agenda-2024-2034",
        "status": "supporting",
        "priority_rank": 15,
        "selected_source_file": "sources/15-maatschappelijke-agenda-2024-2034.html",
    },
    {
        "source_number": 16,
        "document_id": "mun_almere_2024_2026_visie_gezondheidsbeleid",
        "title": "Visie Gezondheidsbeleid Almere 2024-2026",
        "short_title": "Visie gezondheidsbeleid Almere",
        "publisher": "Raad van Almere",
        "publication_date": "2024-04-18",
        "document_type": "municipal_policy_summary",
        "jurisdiction_level": "municipal",
        "source_url": "https://raadvanalmere.nl/article/visie-gezondheidsbeleid-almere-2024-2026",
        "status": "supporting",
        "priority_rank": 16,
        "selected_source_file": "sources/16-visie-gezondheidsbeleid-almere-2024-2026.html",
    },
    {
        "source_number": 17,
        "document_id": "mun_almere_pga_transformatieplan",
        "title": "Transformatieplan Positief Gezond Almere",
        "short_title": "PGA transformatieplan",
        "publisher": "Positief Gezond Almere",
        "publication_date": "2025-05-01",
        "document_type": "implementation_plan",
        "jurisdiction_level": "municipal",
        "source_url": "https://positiefgezondalmere.nl/over-ons/",
        "status": "current",
        "priority_rank": 5,
        "selected_source_file": "sources/17-over-ons__Transformatieplan_Positief_Gezond_Almere.pdf",
    },
    {
        "source_number": 18,
        "document_id": "mun_almere_pga_seo_businesscase_2024",
        "title": "Naar een positief gezond Almere; Beleidstheorie en businesscase transformatieplan",
        "short_title": "SEO beleidstheorie en businesscase PGA",
        "publisher": "SEO Economisch Onderzoek",
        "publication_date": "2024-04-25",
        "document_type": "research_report",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.seo.nl/publicaties/naar-een-positief-gezond-almere-beleidstheorie-en-businesscase-transformatieplan/",
        "status": "reference",
        "priority_rank": 11,
        "selected_source_file": "sources/18-naar-een-positief-gezond-almere-beleidstheorie-en-businesscase-transformatieplan__2021-61-Naar-een-gezond-positief-Almere_Wouter-Vermeulen.pdf",
    },
    {
        "source_number": 46,
        "document_id": "mun_almere_2026_stevige_lokale_teams_raad",
        "title": "Stevige Lokale Teams en inzet Investeringsfonds jeugd en gezin",
        "short_title": "Stevige Lokale Teams Almere",
        "publisher": "Raad van Almere",
        "publication_date": "2026-01-06",
        "document_type": "municipal_council_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://raadvanalmere.nl/article/stevige-lokale-teams-en-inzet-investeringsfonds-jeugd-en-gezin1",
        "status": "current",
        "priority_rank": 28,
        "selected_source_file": "sources/46-stevige-lokale-teams-en-inzet-investeringsfonds-jeugd-en-gezin.html",
    },
    {
        "source_number": 47,
        "document_id": "mun_almere_wijkteams",
        "title": "Wijkteams Almere",
        "short_title": "Wijkteams Almere",
        "publisher": "Wijkteams Almere / Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_service_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://wijkteams.almere.nl/",
        "status": "current",
        "priority_rank": 29,
        "selected_source_file": "sources/47-wijkteams-almere.html",
    },
    {
        "source_number": 48,
        "document_id": "nat_vng_richtinggevend_kader_toegang_lokale_teams",
        "title": "Richtinggevend kader toegang, lokale teams en integrale dienstverlening",
        "short_title": "VNG richtinggevend kader lokale teams",
        "publisher": "VNG",
        "publication_date": "2024-03-01",
        "document_type": "implementation_framework",
        "jurisdiction_level": "national",
        "source_url": "https://vng.nl/publicaties/richtinggevend-kader-toegang-lokale-teams-en-integrale-dienstverlening",
        "status": "reference",
        "priority_rank": 30,
        "selected_source_file": "sources/48-richtinggevend-kader-toegang-lokale-teams-en-integrale-dienstverlening.pdf",
    },
    {
        "source_number": 49,
        "document_id": "nat_tsd_basisfuncties_lokale_teams",
        "title": "Basisfuncties voor lokale teams",
        "short_title": "Basisfuncties lokale teams",
        "publisher": "Toezicht Sociaal Domein",
        "publication_date": "2021-10-06",
        "document_type": "assessment_framework",
        "jurisdiction_level": "national",
        "source_url": "https://www.toezichtsociaaldomein.nl/documenten/2021/10/06/basisfuncties-voor-lokale-teams",
        "status": "reference",
        "priority_rank": 31,
        "selected_source_file": "sources/49-basisfuncties-voor-lokale-teams.html",
    },
    {
        "source_number": 50,
        "document_id": "reg_ggd_flevoland_begroting_2026",
        "title": "Begroting 2026 GGD Flevoland",
        "short_title": "GGD Flevoland begroting 2026",
        "publisher": "GGD Flevoland",
        "publication_date": "2025-10-14",
        "document_type": "regional_budget",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/app/uploads/sites/6/2025/10/Begroting-2026-GGD-Flevoland.pdf",
        "status": "current",
        "priority_rank": 32,
        "selected_source_file": "sources/50-begroting-2026-ggd-flevoland.pdf",
    },
    {
        "source_number": 51,
        "document_id": "reg_ggd_flevoland_kennis_en_advies",
        "title": "Kennis en Advies",
        "short_title": "GGD Flevoland Kennis en Advies",
        "publisher": "GGD Flevoland",
        "publication_date": None,
        "document_type": "regional_service_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/professional/kennis-en-advies/",
        "status": "current",
        "priority_rank": 33,
        "selected_source_file": "sources/51-kennis-en-advies-ggd-flevoland.html",
    },
    {
        "source_number": 52,
        "document_id": "reg_ggd_flevoland_jgz_almere_profile",
        "title": "Profiel Jeugdgezondheidszorg",
        "short_title": "JGZ Almere profiel",
        "publisher": "GGD Flevoland",
        "publication_date": None,
        "document_type": "regional_service_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/professional/jeugdgezondheidszorg/",
        "status": "current",
        "priority_rank": 34,
        "selected_source_file": "sources/52-profiel-jeugdgezondheidszorg-ggd-flevoland.html",
    },
    {
        "source_number": 53,
        "document_id": "mun_almere_2026_stevige_lokale_teams_geamendeerd_raadsvoorstel",
        "title": "Stevige Lokale Teams en inzet Investeringsfonds jeugd en gezin - geamendeerd raadsvoorstel",
        "short_title": "SLT geamendeerd raadsvoorstel",
        "publisher": "Raad van Almere",
        "publication_date": "2026-02-19",
        "document_type": "municipal_council_proposal",
        "jurisdiction_level": "municipal",
        "source_url": "https://api.notubiz.nl/document/16660072/2",
        "status": "current",
        "priority_rank": 35,
        "selected_source_file": "sources/53-stevige-lokale-teams-geamendeerd-raadsvoorstel.pdf",
    },
    {
        "source_number": 54,
        "document_id": "mun_almere_2026_stevige_lokale_teams_raadsvoorstel",
        "title": "Stevige Lokale Teams en inzet Investeringsfonds jeugd en gezin - raadsvoorstel",
        "short_title": "SLT raadsvoorstel",
        "publisher": "Raad van Almere",
        "publication_date": "2026-01-15",
        "document_type": "municipal_council_proposal",
        "jurisdiction_level": "municipal",
        "source_url": "https://api.notubiz.nl/document/16466623/1",
        "status": "reference",
        "priority_rank": 36,
        "selected_source_file": "sources/54-stevige-lokale-teams-raadsvoorstel.pdf",
    },
    {
        "source_number": 55,
        "document_id": "mun_almere_2026_stevige_lokale_teams_begrotingswijziging",
        "title": "Stevige Lokale Teams en inzet Investeringsfonds jeugd en gezin - begrotingswijziging",
        "short_title": "SLT begrotingswijziging",
        "publisher": "Raad van Almere",
        "publication_date": "2026-01-15",
        "document_type": "municipal_budget_change",
        "jurisdiction_level": "municipal",
        "source_url": "https://api.notubiz.nl/document/16421447/1",
        "status": "reference",
        "priority_rank": 37,
        "selected_source_file": "sources/55-stevige-lokale-teams-begrotingswijziging.pdf",
    },
    {
        "source_number": 56,
        "document_id": "mun_almere_2026_stevige_lokale_teams_besluitenlijst",
        "title": "Stevige Lokale Teams en inzet Investeringsfonds jeugd en gezin - besluitenlijst",
        "short_title": "SLT besluitenlijst",
        "publisher": "Raad van Almere",
        "publication_date": "2026-01-15",
        "document_type": "municipal_decision_list",
        "jurisdiction_level": "municipal",
        "source_url": "https://api.notubiz.nl/document/16520063/2",
        "status": "reference",
        "priority_rank": 38,
        "selected_source_file": "sources/56-stevige-lokale-teams-besluitenlijst.pdf",
    },
    {
        "source_number": 57,
        "document_id": "mun_almere_samenwerkingsprojecten",
        "title": "Samenwerkingsprojecten",
        "short_title": "Samenwerkingsprojecten Almere",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_project_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/wonen-en-zorg/informatie-voor-onze-partners/samenwerkingsprojecten",
        "status": "current",
        "priority_rank": 39,
        "selected_source_file": "sources/57-samenwerkingsprojecten-almere.html",
    },
    {
        "source_number": 58,
        "document_id": "mun_almere_pga_current_home",
        "title": "Positief Gezond Almere",
        "short_title": "Positief Gezond Almere actueel",
        "publisher": "Positief Gezond Almere",
        "publication_date": None,
        "document_type": "municipal_program_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://positiefgezondalmere.nl/",
        "status": "current",
        "priority_rank": 40,
        "selected_source_file": "sources/58-positief-gezond-almere-current-home.html",
    },
    {
        "source_number": 59,
        "document_id": "mun_almere_gezonde_scholen",
        "title": "Gezonde scholen",
        "short_title": "Gezonde scholen Almere",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/gezond-in-almere/gezonde-scholen",
        "status": "current",
        "priority_rank": 41,
        "selected_source_file": "sources/59-gezonde-scholen-almere.html",
    },
    {
        "source_number": 60,
        "document_id": "mun_almere_gezond_in_almere",
        "title": "Gezond in Almere",
        "short_title": "Gezond in Almere",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/gezond-in-almere",
        "status": "current",
        "priority_rank": 42,
        "selected_source_file": "sources/60-gezond-in-almere.html",
    },
    {
        "source_number": 61,
        "document_id": "reg_ggd_flevoland_gezonde_school",
        "title": "De Gezonde School",
        "short_title": "GGD Flevoland Gezonde School",
        "publisher": "GGD Flevoland",
        "publication_date": None,
        "document_type": "regional_service_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/professional/scholen-en-kinderopvang/gezonde-school/",
        "status": "current",
        "priority_rank": 43,
        "selected_source_file": "sources/61-gezonde-school-ggd-flevoland.html",
    },
    {
        "source_number": 62,
        "document_id": "reg_ggd_flevoland_ketenaanpak_gezond_gewicht_almere",
        "title": "Ketenaanpak gezond gewicht - Gezond Gewicht Almere",
        "short_title": "GGD Ketenaanpak Gezond Gewicht Almere",
        "publisher": "GGD Flevoland",
        "publication_date": None,
        "document_type": "regional_service_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/professional/gemeenten/ketenaanpak-gezond-gewicht/",
        "status": "current",
        "priority_rank": 44,
        "selected_source_file": "sources/62-ketenaanpak-gezond-gewicht-ggd-flevoland.html",
    },
    {
        "source_number": 63,
        "document_id": "mun_almere_lea_2024_2028",
        "title": "LEA 2024-2028",
        "short_title": "LEA 2024-2028 Almere",
        "publisher": "Sociaal Domein Almere / Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://sociaaldomein.almere.nl/onderwijs/lea-2024-2028",
        "status": "current",
        "priority_rank": 45,
        "selected_source_file": "sources/63-lea-2024-2028-sociaal-domein-almere.html",
    },
]


TRACKED_EMPTY_DIRECTORIES = [
    "config",
    "prompts",
    "tests",
    "docs",
    "data/intermediate/text",
    "data/intermediate/chunks",
    "data/intermediate/tables",
    "data/extracted/documents",
    "data/extracted/claims",
    "data/extracted/municipal",
    "data/schemas",
    "data/logs",
]


def write_gitkeep(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    gitkeep = directory / ".gitkeep"
    gitkeep.write_text("", encoding="utf-8")


def manifest_entry_for_document(doc: dict, level_dirs: dict[str, Path]) -> dict:
    source_path = REPO_ROOT / doc["selected_source_file"]
    if not source_path.exists():
        raise FileNotFoundError(f"Missing source file: {source_path}")

    ext = source_path.suffix.lower()
    destination_dir = level_dirs[doc["jurisdiction_level"]]
    destination_path = destination_dir / f"{doc['document_id']}{ext}"
    copy2(source_path, destination_path)

    return {
        "document_id": doc["document_id"],
        "title": doc["title"],
        "short_title": doc["short_title"],
        "publisher": doc["publisher"],
        "publication_date": doc["publication_date"],
        "document_type": doc["document_type"],
        "jurisdiction_level": doc["jurisdiction_level"],
        "file_path": destination_path.relative_to(REPO_ROOT).as_posix(),
        "source_url": doc["source_url"],
        "status": doc["status"],
        "priority_rank": doc["priority_rank"],
        "source_number": doc["source_number"],
        "selected_source_file": doc["selected_source_file"],
    }


def load_preserved_manifest_entries(manifest_path: Path, managed_document_ids: set[str]) -> list[dict]:
    if not manifest_path.exists():
        return []

    entries = json.loads(manifest_path.read_text(encoding="utf-8"))
    preserved = []
    for entry in entries:
        if entry["document_id"] in managed_document_ids:
            continue
        raw_path = REPO_ROOT / entry["file_path"]
        if not raw_path.exists():
            raise FileNotFoundError(f"Existing manifest entry points to missing raw file: {raw_path}")
        preserved.append(entry)
    return preserved


def main() -> None:
    raw_root = REPO_ROOT / "data" / "raw"
    level_dirs = {
        "national": raw_root / "national",
        "regional": raw_root / "regional",
        "municipal": raw_root / "municipal",
    }

    for directory in level_dirs.values():
        directory.mkdir(parents=True, exist_ok=True)

    for relative_dir in TRACKED_EMPTY_DIRECTORIES:
        write_gitkeep(REPO_ROOT / relative_dir)

    manifest_path = raw_root / "manifest.json"
    managed_document_ids = {doc["document_id"] for doc in DOCUMENTS}
    manifest_entries = load_preserved_manifest_entries(manifest_path, managed_document_ids)
    manifest_entries.extend(manifest_entry_for_document(doc, level_dirs) for doc in DOCUMENTS)

    manifest_entries.sort(key=lambda item: item["priority_rank"])
    manifest_path.write_text(
        json.dumps(manifest_entries, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    print(f"Wrote {manifest_path.relative_to(REPO_ROOT).as_posix()}")
    print(f"Prepared {len(manifest_entries)} Phase 0 source documents")


if __name__ == "__main__":
    main()
