from __future__ import annotations

import json
from pathlib import Path
from shutil import copy2


REPO_ROOT = Path(__file__).resolve().parents[1]


DOCUMENTS = [
    {
        "source_number": 1,
        "document_id": "nat_azwa_2025_definitief",
        "title": "Aanvullend Zorg- en Welzijnsakkoord (AZWA) (Definitief)",
        "short_title": "AZWA definitief",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2025-08-31",
        "document_type": "agreement",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/rapporten/2025/08/31/aanvullend-zorg-en-welzijnsakkoord-azwa",
        "status": "current",
        "priority_rank": 1,
        "selected_source_file": "sources/01-aanvullend-zorg-en-welzijnsakkoord-azwa__PDIZA-1087289TK_B_Aanvullend_Zorg-_en_Welzijnsakkoord_AZWA_.pdf",
    },
    {
        "source_number": 2,
        "document_id": "nat_azwa_2025_aanbiedingsbrief",
        "title": "Kamerbrief aanbieding Aanvullend Zorg- en Welzijnsakkoord (AZWA)",
        "short_title": "Kamerbrief aanbieding AZWA",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2025-09-08",
        "document_type": "kamerbrief",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/kamerstukken/2025/09/08/kamerbrief-over-aanbieding-aanvullend-zorg-en-welzijnsakkoord-azwa",
        "status": "reference",
        "priority_rank": 8,
        "selected_source_file": "sources/02-kamerbrief-over-aanbieding-aanvullend-zorg-en-welzijnsakkoord-azwa__PDIZA-1087289TK_A.pdf",
    },
    {
        "source_number": 3,
        "document_id": "nat_azwa_2026_cw31_kamerbrief",
        "title": "Kamerbrief over CW 3.1 kaders voor AZWA onderdelen",
        "short_title": "Kamerbrief CW 3.1 kaders AZWA",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2026-03-10",
        "document_type": "kamerbrief",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/kamerstukken/2026/03/10/kamerbrief-over-cw3-1-kaders-voor-azwa-onderdelen",
        "status": "current",
        "priority_rank": 6,
        "selected_source_file": "sources/03-kamerbrief-over-cw3-1-kaders-voor-azwa-onderdelen__FEZ-1094401_A.pdf",
    },
    {
        "source_number": 4,
        "document_id": "nat_azwa_2026_cw31_kader_d5_d6",
        "title": "CW 3.1 kader basisfunctionaliteiten en basisinfrastructuur D5 en D6",
        "short_title": "CW 3.1 kader D5/D6",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2026-03-10",
        "document_type": "framework",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/publicaties/2026/03/10/cw-3-1-kader-basisfunctionaliteiten-en-basisinfrastructuur-d5-en-d6",
        "status": "current",
        "priority_rank": 3,
        "selected_source_file": "sources/04-cw-3-1-kader-basisfunctionaliteiten-en-basisinfrastructuur-d5-en-d6__FEZ-1094401_C_CW_3.1_kader_Basisfunctionaliteiten_en_basisinfrastructuur-_D5_en_D6.pdf",
    },
    {
        "source_number": 5,
        "document_id": "nat_azwa_2026_voortgang_kamerbrief",
        "title": "Kamerbrief inzake voortgang Integraal Zorgakkoord (IZA) en Aanvullend Zorg- en Welzijnsakkoord (AZWA)",
        "short_title": "Voortgangsbrief IZA/AZWA",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2026-04-09",
        "document_type": "kamerbrief",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/kamerstukken/2026/04/09/kamerbrief-inzake-voortgang-integraal-zorgakkoord-iza-en-aanvullend-zorg-en-welzijnsakkoord-azwa",
        "status": "current",
        "priority_rank": 7,
        "selected_source_file": "sources/05-kamerbrief-inzake-voortgang-integraal-zorgakkoord-iza-en-aanvullend-zorg-en-welzijnsakkoord-azwa__PDIZA-1095964_A.pdf",
    },
    {
        "source_number": 6,
        "document_id": "nat_azwa_2025_onderhandelaarsakkoord",
        "title": "Aanvullend Zorg- en Welzijnsakkoord - onderhandelaarsakkoord",
        "short_title": "AZWA onderhandelaarsakkoord",
        "publisher": "VNG",
        "publication_date": "2025-07-11",
        "document_type": "agreement",
        "jurisdiction_level": "national",
        "source_url": "https://vng.nl/brieven/onderhandelaarsakkoord-aanvullend-zorg-en-welzijnsakkoord-azwa",
        "status": "reference",
        "priority_rank": 2,
        "selected_source_file": "sources/06-onderhandelaarsakkoord-aanvullend-zorg-en-welzijnsakkoord-azwa__PDIZA-1085052_B_Aanvullend_Zorg-_en_Welzijnsakkoord_-_onderhandelaarsakkoord.pdf",
    },
    {
        "source_number": 7,
        "document_id": "nat_vng_azwa_faq_middelen",
        "title": "Welke middelen zijn beschikbaar in het AZWA en hoe worden deze middelen verdeeld?",
        "short_title": "VNG FAQ middelen AZWA",
        "publisher": "VNG",
        "publication_date": None,
        "document_type": "faq",
        "jurisdiction_level": "national",
        "source_url": "https://vng.nl/vragen-en-antwoorden/welke-middelen-zijn-beschikbaar-in-het-azwa-en-hoe-worden-deze-middelen-verdeeld",
        "status": "supporting",
        "priority_rank": 13,
        "selected_source_file": "sources/07-welke-middelen-zijn-beschikbaar-in-het-azwa-en-hoe-worden-deze-middelen-verdeeld.html",
    },
    {
        "source_number": 8,
        "document_id": "nat_vng_azwa_faq_uitvoeringscapaciteit",
        "title": "Is er rekening gehouden met de benodigde uitvoeringscapaciteit van gemeenten bij het AZWA?",
        "short_title": "VNG FAQ uitvoeringscapaciteit AZWA",
        "publisher": "VNG",
        "publication_date": None,
        "document_type": "faq",
        "jurisdiction_level": "national",
        "source_url": "https://vng.nl/vragen-en-antwoorden/is-er-rekening-gehouden-met-de-benodigde-uitvoeringscapaciteit-van-gemeenten-bij-het-azwa",
        "status": "supporting",
        "priority_rank": 14,
        "selected_source_file": "sources/08-is-er-rekening-gehouden-met-de-benodigde-uitvoeringscapaciteit-van-gemeenten-bij-het-azwa.html",
    },
    {
        "source_number": 9,
        "document_id": "nat_iza_2022_integraal_zorgakkoord",
        "title": "Integraal Zorgakkoord: Samen werken aan gezonde zorg",
        "short_title": "IZA 2022",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2022-09-16",
        "document_type": "agreement",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/rapporten/2022/09/16/integraal-zorgakkoord-samen-werken-aan-gezonde-zorg",
        "status": "reference",
        "priority_rank": 9,
        "selected_source_file": "sources/09-integraal-zorgakkoord-samen-werken-aan-gezonde-zorg__integraal-zorg-akkoord.pdf",
    },
    {
        "source_number": 10,
        "document_id": "nat_gala_2023_gezond_en_actief_leven",
        "title": "GALA - Gezond en Actief Leven Akkoord",
        "short_title": "GALA 2023",
        "publisher": "Ministerie van Volksgezondheid, Welzijn en Sport",
        "publication_date": "2023-01-31",
        "document_type": "agreement",
        "jurisdiction_level": "national",
        "source_url": "https://www.rijksoverheid.nl/documenten/rapporten/2023/01/31/gala-gezond-en-actief-leven-akkoord",
        "status": "reference",
        "priority_rank": 10,
        "selected_source_file": "sources/10-gala-gezond-en-actief-leven-akkoord__gala-gezond-en-actief-leven-akkoord.pdf",
    },
    {
        "source_number": 11,
        "document_id": "reg_flevoland_2023_regiobeeld",
        "title": "Regiobeeld Flevoland 2023",
        "short_title": "Regiobeeld Flevoland 2023",
        "publisher": "Flever",
        "publication_date": "2023-07-12",
        "document_type": "regional_report",
        "jurisdiction_level": "regional",
        "source_url": "https://flever.nl/kennisbank/regiobeeld-flevoland-2023/",
        "status": "reference",
        "priority_rank": 12,
        "selected_source_file": "sources/11-regiobeeld-flevoland-2023__Regiobeeld-Flevoland.pdf",
    },
    {
        "source_number": 12,
        "document_id": "reg_flevoland_2023_regioplan_iza",
        "title": "Zorgzaam Flevoland 2023 Regioplan IZA Flevoland",
        "short_title": "Regioplan IZA Flevoland",
        "publisher": "Zorgzaam Flevoland / Flever",
        "publication_date": "2023-12-22",
        "document_type": "regional_plan",
        "jurisdiction_level": "regional",
        "source_url": "https://flever.nl/wp-content/uploads/2024/01/Regioplan_IZA_Flevoland_ZorgzaamFlevoland2023.pdf",
        "status": "reference",
        "priority_rank": 4,
        "selected_source_file": "sources/12-regioplan_iza_flevoland_zorgzaamflevoland2023__Regioplan_IZA_Flevoland_ZorgzaamFlevoland2023.pdf",
    },
    {
        "source_number": 13,
        "document_id": "mun_almere_sociaal_domein_informatiepagina",
        "title": "Informatiepagina Sociaal Domein",
        "short_title": "Sociaal domein informatiepagina",
        "publisher": "Raad van Almere",
        "publication_date": "2026-03-25",
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://raadvanalmere.nl/page/informatiepagina-sociaal-domein",
        "status": "supporting",
        "priority_rank": 17,
        "selected_source_file": "sources/13-informatiepagina-sociaal-domein.html",
    },
    {
        "source_number": 14,
        "document_id": "mun_almere_sociale_staat_gateway",
        "title": "Sociale staat van Almere",
        "short_title": "Sociale staat van Almere gateway",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_gateway_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/sociale-staat-van-almere",
        "status": "supporting",
        "priority_rank": 18,
        "selected_source_file": "sources/14-sociale-staat-van-almere.html",
    },
    {
        "source_number": 15,
        "document_id": "mun_almere_2024_2034_maatschappelijke_agenda",
        "title": "Maatschappelijke agenda 2024-2034",
        "short_title": "Maatschappelijke agenda 2024-2034",
        "publisher": "Raad van Almere",
        "publication_date": "2024-06-10",
        "document_type": "municipal_policy_summary",
        "jurisdiction_level": "municipal",
        "source_url": "https://raadvanalmere.nl/article/maatschappelijke-agenda-2024-2034",
        "status": "supporting",
        "priority_rank": 15,
        "selected_source_file": "sources/15-maatschappelijke-agenda-2024-2034.html",
    },
    {
        "source_number": 16,
        "document_id": "mun_almere_2024_2026_visie_gezondheidsbeleid",
        "title": "Visie Gezondheidsbeleid Almere 2024-2026",
        "short_title": "Visie gezondheidsbeleid Almere",
        "publisher": "Raad van Almere",
        "publication_date": "2024-04-18",
        "document_type": "municipal_policy_summary",
        "jurisdiction_level": "municipal",
        "source_url": "https://raadvanalmere.nl/article/visie-gezondheidsbeleid-almere-2024-2026",
        "status": "supporting",
        "priority_rank": 16,
        "selected_source_file": "sources/16-visie-gezondheidsbeleid-almere-2024-2026.html",
    },
    {
        "source_number": 17,
        "document_id": "mun_almere_pga_transformatieplan",
        "title": "Transformatieplan Positief Gezond Almere",
        "short_title": "PGA transformatieplan",
        "publisher": "Positief Gezond Almere",
        "publication_date": "2025-05-01",
        "document_type": "implementation_plan",
        "jurisdiction_level": "municipal",
        "source_url": "https://positiefgezondalmere.nl/over-ons/",
        "status": "current",
        "priority_rank": 5,
        "selected_source_file": "sources/17-over-ons__Transformatieplan_Positief_Gezond_Almere.pdf",
    },
    {
        "source_number": 18,
        "document_id": "mun_almere_pga_seo_businesscase_2024",
        "title": "Naar een positief gezond Almere; Beleidstheorie en businesscase transformatieplan",
        "short_title": "SEO beleidstheorie en businesscase PGA",
        "publisher": "SEO Economisch Onderzoek",
        "publication_date": "2024-04-25",
        "document_type": "research_report",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.seo.nl/publicaties/naar-een-positief-gezond-almere-beleidstheorie-en-businesscase-transformatieplan/",
        "status": "reference",
        "priority_rank": 11,
        "selected_source_file": "sources/18-naar-een-positief-gezond-almere-beleidstheorie-en-businesscase-transformatieplan__2021-61-Naar-een-gezond-positief-Almere_Wouter-Vermeulen.pdf",
    },
    {
        "source_number": 46,
        "document_id": "mun_almere_2026_stevige_lokale_teams_raad",
        "title": "Stevige Lokale Teams en inzet Investeringsfonds jeugd en gezin",
        "short_title": "Stevige Lokale Teams Almere",
        "publisher": "Raad van Almere",
        "publication_date": "2026-01-06",
        "document_type": "municipal_council_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://raadvanalmere.nl/article/stevige-lokale-teams-en-inzet-investeringsfonds-jeugd-en-gezin1",
        "status": "current",
        "priority_rank": 28,
        "selected_source_file": "sources/46-stevige-lokale-teams-en-inzet-investeringsfonds-jeugd-en-gezin.html",
    },
    {
        "source_number": 47,
        "document_id": "mun_almere_wijkteams",
        "title": "Wijkteams Almere",
        "short_title": "Wijkteams Almere",
        "publisher": "Wijkteams Almere / Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_service_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://wijkteams.almere.nl/",
        "status": "current",
        "priority_rank": 29,
        "selected_source_file": "sources/47-wijkteams-almere.html",
    },
    {
        "source_number": 48,
        "document_id": "nat_vng_richtinggevend_kader_toegang_lokale_teams",
        "title": "Richtinggevend kader toegang, lokale teams en integrale dienstverlening",
        "short_title": "VNG richtinggevend kader lokale teams",
        "publisher": "VNG",
        "publication_date": "2024-03-01",
        "document_type": "implementation_framework",
        "jurisdiction_level": "national",
        "source_url": "https://vng.nl/publicaties/richtinggevend-kader-toegang-lokale-teams-en-integrale-dienstverlening",
        "status": "reference",
        "priority_rank": 30,
        "selected_source_file": "sources/48-richtinggevend-kader-toegang-lokale-teams-en-integrale-dienstverlening.pdf",
    },
    {
        "source_number": 49,
        "document_id": "nat_tsd_basisfuncties_lokale_teams",
        "title": "Basisfuncties voor lokale teams",
        "short_title": "Basisfuncties lokale teams",
        "publisher": "Toezicht Sociaal Domein",
        "publication_date": "2021-10-06",
        "document_type": "assessment_framework",
        "jurisdiction_level": "national",
        "source_url": "https://www.toezichtsociaaldomein.nl/documenten/2021/10/06/basisfuncties-voor-lokale-teams",
        "status": "reference",
        "priority_rank": 31,
        "selected_source_file": "sources/49-basisfuncties-voor-lokale-teams.html",
    },
    {
        "source_number": 50,
        "document_id": "reg_ggd_flevoland_begroting_2026",
        "title": "Begroting 2026 GGD Flevoland",
        "short_title": "GGD Flevoland begroting 2026",
        "publisher": "GGD Flevoland",
        "publication_date": "2025-10-14",
        "document_type": "regional_budget",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/app/uploads/sites/6/2025/10/Begroting-2026-GGD-Flevoland.pdf",
        "status": "current",
        "priority_rank": 32,
        "selected_source_file": "sources/50-begroting-2026-ggd-flevoland.pdf",
    },
    {
        "source_number": 51,
        "document_id": "reg_ggd_flevoland_kennis_en_advies",
        "title": "Kennis en Advies",
        "short_title": "GGD Flevoland Kennis en Advies",
        "publisher": "GGD Flevoland",
        "publication_date": None,
        "document_type": "regional_service_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/professional/kennis-en-advies/",
        "status": "current",
        "priority_rank": 33,
        "selected_source_file": "sources/51-kennis-en-advies-ggd-flevoland.html",
    },
    {
        "source_number": 52,
        "document_id": "reg_ggd_flevoland_jgz_almere_profile",
        "title": "Profiel Jeugdgezondheidszorg",
        "short_title": "JGZ Almere profiel",
        "publisher": "GGD Flevoland",
        "publication_date": None,
        "document_type": "regional_service_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/professional/jeugdgezondheidszorg/",
        "status": "current",
        "priority_rank": 34,
        "selected_source_file": "sources/52-profiel-jeugdgezondheidszorg-ggd-flevoland.html",
    },
    {
        "source_number": 53,
        "document_id": "mun_almere_2026_stevige_lokale_teams_geamendeerd_raadsvoorstel",
        "title": "Stevige Lokale Teams en inzet Investeringsfonds jeugd en gezin - geamendeerd raadsvoorstel",
        "short_title": "SLT geamendeerd raadsvoorstel",
        "publisher": "Raad van Almere",
        "publication_date": "2026-02-19",
        "document_type": "municipal_council_proposal",
        "jurisdiction_level": "municipal",
        "source_url": "https://api.notubiz.nl/document/16660072/2",
        "status": "current",
        "priority_rank": 35,
        "selected_source_file": "sources/53-stevige-lokale-teams-geamendeerd-raadsvoorstel.pdf",
    },
    {
        "source_number": 54,
        "document_id": "mun_almere_2026_stevige_lokale_teams_raadsvoorstel",
        "title": "Stevige Lokale Teams en inzet Investeringsfonds jeugd en gezin - raadsvoorstel",
        "short_title": "SLT raadsvoorstel",
        "publisher": "Raad van Almere",
        "publication_date": "2026-01-15",
        "document_type": "municipal_council_proposal",
        "jurisdiction_level": "municipal",
        "source_url": "https://api.notubiz.nl/document/16466623/1",
        "status": "reference",
        "priority_rank": 36,
        "selected_source_file": "sources/54-stevige-lokale-teams-raadsvoorstel.pdf",
    },
    {
        "source_number": 55,
        "document_id": "mun_almere_2026_stevige_lokale_teams_begrotingswijziging",
        "title": "Stevige Lokale Teams en inzet Investeringsfonds jeugd en gezin - begrotingswijziging",
        "short_title": "SLT begrotingswijziging",
        "publisher": "Raad van Almere",
        "publication_date": "2026-01-15",
        "document_type": "municipal_budget_change",
        "jurisdiction_level": "municipal",
        "source_url": "https://api.notubiz.nl/document/16421447/1",
        "status": "reference",
        "priority_rank": 37,
        "selected_source_file": "sources/55-stevige-lokale-teams-begrotingswijziging.pdf",
    },
    {
        "source_number": 56,
        "document_id": "mun_almere_2026_stevige_lokale_teams_besluitenlijst",
        "title": "Stevige Lokale Teams en inzet Investeringsfonds jeugd en gezin - besluitenlijst",
        "short_title": "SLT besluitenlijst",
        "publisher": "Raad van Almere",
        "publication_date": "2026-01-15",
        "document_type": "municipal_decision_list",
        "jurisdiction_level": "municipal",
        "source_url": "https://api.notubiz.nl/document/16520063/2",
        "status": "reference",
        "priority_rank": 38,
        "selected_source_file": "sources/56-stevige-lokale-teams-besluitenlijst.pdf",
    },
    {
        "source_number": 57,
        "document_id": "mun_almere_samenwerkingsprojecten",
        "title": "Samenwerkingsprojecten",
        "short_title": "Samenwerkingsprojecten Almere",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_project_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/wonen-en-zorg/informatie-voor-onze-partners/samenwerkingsprojecten",
        "status": "current",
        "priority_rank": 39,
        "selected_source_file": "sources/57-samenwerkingsprojecten-almere.html",
    },
    {
        "source_number": 58,
        "document_id": "mun_almere_pga_current_home",
        "title": "Positief Gezond Almere",
        "short_title": "Positief Gezond Almere actueel",
        "publisher": "Positief Gezond Almere",
        "publication_date": None,
        "document_type": "municipal_program_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://positiefgezondalmere.nl/",
        "status": "current",
        "priority_rank": 40,
        "selected_source_file": "sources/58-positief-gezond-almere-current-home.html",
    },
    {
        "source_number": 59,
        "document_id": "mun_almere_gezonde_scholen",
        "title": "Gezonde scholen",
        "short_title": "Gezonde scholen Almere",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/gezond-in-almere/gezonde-scholen",
        "status": "current",
        "priority_rank": 41,
        "selected_source_file": "sources/59-gezonde-scholen-almere.html",
    },
    {
        "source_number": 60,
        "document_id": "mun_almere_gezond_in_almere",
        "title": "Gezond in Almere",
        "short_title": "Gezond in Almere",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/gezond-in-almere",
        "status": "current",
        "priority_rank": 42,
        "selected_source_file": "sources/60-gezond-in-almere.html",
    },
    {
        "source_number": 61,
        "document_id": "reg_ggd_flevoland_gezonde_school",
        "title": "De Gezonde School",
        "short_title": "GGD Flevoland Gezonde School",
        "publisher": "GGD Flevoland",
        "publication_date": None,
        "document_type": "regional_service_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/professional/scholen-en-kinderopvang/gezonde-school/",
        "status": "current",
        "priority_rank": 43,
        "selected_source_file": "sources/61-gezonde-school-ggd-flevoland.html",
    },
    {
        "source_number": 62,
        "document_id": "reg_ggd_flevoland_ketenaanpak_gezond_gewicht_almere",
        "title": "Ketenaanpak gezond gewicht - Gezond Gewicht Almere",
        "short_title": "GGD Ketenaanpak Gezond Gewicht Almere",
        "publisher": "GGD Flevoland",
        "publication_date": None,
        "document_type": "regional_service_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/professional/gemeenten/ketenaanpak-gezond-gewicht/",
        "status": "current",
        "priority_rank": 44,
        "selected_source_file": "sources/62-ketenaanpak-gezond-gewicht-ggd-flevoland.html",
    },
    {
        "source_number": 63,
        "document_id": "mun_almere_lea_2024_2028",
        "title": "LEA 2024-2028",
        "short_title": "LEA 2024-2028 Almere",
        "publisher": "Sociaal Domein Almere / Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://sociaaldomein.almere.nl/onderwijs/lea-2024-2028",
        "status": "current",
        "priority_rank": 45,
        "selected_source_file": "sources/63-lea-2024-2028-sociaal-domein-almere.html",
    },
    {
        "source_number": 64,
        "document_id": "nat_zorgakkoorden_pga_20_miljoen_2024",
        "title": "20 miljoen voor transformatieplan Positief Gezond Almere",
        "short_title": "Zorgakkoorden 20 miljoen PGA",
        "publisher": "Zorgakkoorden / Ministerie van VWS",
        "publication_date": "2024-12-11",
        "document_type": "national_news_page",
        "jurisdiction_level": "national",
        "source_url": "https://www.zorgakkoorden.nl/actueel/nieuws/Transformatieplan_Positief_Mooi_Almere/",
        "status": "current",
        "priority_rank": 46,
        "selected_source_file": "sources/64-zorgakkoorden-20-miljoen-pga.html",
    },
    {
        "source_number": 65,
        "document_id": "mun_almere_pga_regionaal_transferpunt",
        "title": "Regionaal Transferpunt (RTP) Almere",
        "short_title": "PGA Regionaal Transferpunt",
        "publisher": "Positief Gezond Almere",
        "publication_date": None,
        "document_type": "municipal_program_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://positiefgezondalmere.nl/projecten/regionaal-transferpunt/",
        "status": "current",
        "priority_rank": 47,
        "selected_source_file": "sources/65-pga-regionaal-transferpunt.html",
    },
    {
        "source_number": 66,
        "document_id": "reg_flevoziekenhuis_rtp_flevoland_2025",
        "title": "Regionaal Transferpunt Flevoland van start",
        "short_title": "Flevoziekenhuis RTP Flevoland",
        "publisher": "Flevoziekenhuis",
        "publication_date": "2025-01-14",
        "document_type": "provider_news_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.flevoziekenhuis.nl/verwijzers/nieuwsoverzicht-verwijzers/2025/01/regionaal-transferpunt-flevoland-van-start/",
        "status": "current",
        "priority_rank": 48,
        "selected_source_file": "sources/66-flevoziekenhuis-rtp-flevoland.html",
    },
    {
        "source_number": 67,
        "document_id": "reg_rtp_flevoland_home",
        "title": "Regionaal Transferpunt Flevoland",
        "short_title": "RTP Flevoland home",
        "publisher": "RTP Flevoland",
        "publication_date": None,
        "document_type": "regional_service_page",
        "jurisdiction_level": "regional",
        "source_url": "https://rtpflevoland.nl/",
        "status": "current",
        "priority_rank": 49,
        "selected_source_file": "sources/67-rtp-flevoland-home.html",
    },
    {
        "source_number": 68,
        "document_id": "mun_almere_pga_rso_data_infrastructuur",
        "title": "Regionale Samenwerkingsorganisatie (RSO)",
        "short_title": "PGA RSO en data-infrastructuur",
        "publisher": "Positief Gezond Almere",
        "publication_date": None,
        "document_type": "municipal_program_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://positiefgezondalmere.nl/projecten/regionale-samenwerkingsorganisatie-rso/",
        "status": "current",
        "priority_rank": 50,
        "selected_source_file": "sources/68-pga-rso-data-infrastructuur.html",
    },
    {
        "source_number": 69,
        "document_id": "reg_flevoziekenhuis_thuismonitoring",
        "title": "Thuismonitoring en het Flevoziekenhuis",
        "short_title": "Flevoziekenhuis thuismonitoring",
        "publisher": "Flevoziekenhuis",
        "publication_date": None,
        "document_type": "provider_info_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.flevoziekenhuis.nl/opname-bezoek/thuismonitoring-en-het-flevoziekenhuis/",
        "status": "current",
        "priority_rank": 51,
        "selected_source_file": "sources/69-flevoziekenhuis-thuismonitoring.html",
    },
    {
        "source_number": 70,
        "document_id": "reg_ggd_flevoland_kadernota_2027",
        "title": "Kadernota 2027 GGD Flevoland",
        "short_title": "GGD Flevoland Kadernota 2027",
        "publisher": "GGD Flevoland",
        "publication_date": "2026-01-01",
        "document_type": "regional_budget_framework",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/app/uploads/sites/6/2026/01/002025-GGD-Flevo-Kadernota-2026.pdf",
        "status": "current",
        "priority_rank": 52,
        "selected_source_file": "sources/70-ggd-flevoland-kadernota-2027.pdf",
    },
    {
        "source_number": 71,
        "document_id": "reg_woonzorg_flevoland_beleidsplan_2026",
        "title": "Beleidsplan 2026 Woonzorg Flevoland",
        "short_title": "Woonzorg Flevoland beleidsplan 2026",
        "publisher": "Woonzorg Flevoland",
        "publication_date": "2026-01-13",
        "document_type": "provider_policy_plan",
        "jurisdiction_level": "regional",
        "source_url": "https://woonzorgflevoland.nl/wp-content/uploads/Beleidsplan-2026-Woonzorg-Flevoland_DEF.pdf",
        "status": "current",
        "priority_rank": 53,
        "selected_source_file": "sources/71-woonzorg-flevoland-beleidsplan-2026.pdf",
    },
    {
        "source_number": 72,
        "document_id": "reg_npz_almere_pilot_viewer_acp",
        "title": "Pilot viewer-ACP",
        "short_title": "NPZ Almere pilot viewer-ACP",
        "publisher": "Netwerk Palliatieve Zorg Almere",
        "publication_date": None,
        "document_type": "regional_project_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.npzalmere.nl/pilot-viewer-acp/",
        "status": "current",
        "priority_rank": 54,
        "selected_source_file": "sources/72-npz-almere-pilot-viewer-acp.html",
    },
    {
        "source_number": 73,
        "document_id": "reg_npz_almere_evaluatie_viewer_pzp_acp_2025",
        "title": "Evaluatie viewer PZP/ACP pilot Almere 2024-2025",
        "short_title": "NPZ Almere evaluatie viewer PZP/ACP",
        "publisher": "Netwerk Palliatieve Zorg Almere",
        "publication_date": "2025-09-01",
        "document_type": "regional_project_evaluation",
        "jurisdiction_level": "regional",
        "source_url": "https://www.npzalmere.nl/wp-content/uploads/2025/09/Evaluatie-viewer-PZP-ACP-pilot-Almere-20242025-def.pdf",
        "status": "current",
        "priority_rank": 55,
        "selected_source_file": "sources/73-npz-almere-evaluatie-viewer-pzp-acp-2025.pdf",
    },
    {
        "source_number": 74,
        "document_id": "nat_palliaweb_digitale_initiatieven_pzp",
        "title": "Digitale initiatieven proactieve zorgplanning",
        "short_title": "Palliaweb digitale initiatieven PZP",
        "publisher": "Palliaweb / PZNL",
        "publication_date": None,
        "document_type": "national_project_overview",
        "jurisdiction_level": "national",
        "source_url": "https://palliaweb.nl/initiatieven-proactieve-zorgplanning",
        "status": "current",
        "priority_rank": 56,
        "selected_source_file": "sources/74-palliaweb-digitale-initiatieven-pzp.html",
    },
    {
        "source_number": 75,
        "document_id": "reg_npz_almere_jaarplan_2025",
        "title": "Jaarplan 2025 Netwerk Palliatieve Zorg Almere",
        "short_title": "NPZ Almere jaarplan 2025",
        "publisher": "Netwerk Palliatieve Zorg Almere",
        "publication_date": "2025-05-01",
        "document_type": "regional_project_plan",
        "jurisdiction_level": "regional",
        "source_url": "https://www.npzalmere.nl/wp-content/uploads/2025/05/Jaarplan-2025-NPZAlmere-DEF-.pdf",
        "status": "current",
        "priority_rank": 57,
        "selected_source_file": "sources/75-npz-almere-jaarplan-2025.pdf",
    },
    {
        "source_number": 76,
        "document_id": "mun_almere_welzijnskader_2020",
        "title": "Welzijnskader: WELzijn in Almere",
        "short_title": "Welzijnskader Almere",
        "publisher": "Gemeente Almere",
        "publication_date": "2020-01-01",
        "document_type": "municipal_policy",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/fileadmin/files/almere/bestuur_en_organisatie/beleidsstukken/Beleidsnota_s/Welzijnskader__WELzijn_in_Almere_.pdf",
        "status": "current",
        "priority_rank": 58,
        "selected_source_file": "sources/76-welzijnskader-welzijn-in-almere.pdf",
    },
    {
        "source_number": 77,
        "document_id": "mun_almere_subsidie_buurtontmoeting",
        "title": "Financiele ondersteuning voor (buurt)ontmoeting",
        "short_title": "Subsidie buurtontmoeting Almere",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_service_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/subsidies/financiele-ondersteuning-voor-buurtontmoeting",
        "status": "current",
        "priority_rank": 59,
        "selected_source_file": "sources/77-financiele-ondersteuning-buurtontmoeting.html",
    },
    {
        "source_number": 78,
        "document_id": "mun_almere_nadere_regels_buurtontmoeting",
        "title": "Nadere regels (buurt)ontmoetingsplekken en -activiteiten",
        "short_title": "Nadere regels buurtontmoeting Almere",
        "publisher": "Gemeente Almere",
        "publication_date": "2022-06-07",
        "document_type": "municipal_policy",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/subsidies/soorten-subsidies/nadere-regels-buurtontmoetingsplekken-en-activiteiten",
        "status": "current",
        "priority_rank": 60,
        "selected_source_file": "sources/78-nadere-regels-buurtontmoetingsplekken.html",
    },
    {
        "source_number": 79,
        "document_id": "mun_almere_wijkbudget",
        "title": "Wijkbudget",
        "short_title": "Wijkbudget Almere",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_service_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/subsidies/wijkbudget",
        "status": "current",
        "priority_rank": 61,
        "selected_source_file": "sources/79-wijkbudget-almere.html",
    },
    {
        "source_number": 80,
        "document_id": "mun_almere_ondersteuning_mantelzorg",
        "title": "Ondersteuning voor mantelzorg",
        "short_title": "Ondersteuning mantelzorg Almere",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_service_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/mantelzorg/ondersteuning-voor-mantelzorg",
        "status": "current",
        "priority_rank": 62,
        "selected_source_file": "sources/80-ondersteuning-mantelzorg-almere.html",
    },
    {
        "source_number": 81,
        "document_id": "mun_almere_mantelzorgwaardering",
        "title": "Mantelzorgwaardering",
        "short_title": "Mantelzorgwaardering Almere",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_service_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/mantelzorg/mantelzorgwaardering",
        "status": "current",
        "priority_rank": 63,
        "selected_source_file": "sources/81-mantelzorgwaardering-almere.html",
    },
    {
        "source_number": 82,
        "document_id": "mun_almere_sociaal_domein_aanbod_jeugd_gezin",
        "title": "Aanbod jeugd en gezin",
        "short_title": "Sociaal Domein aanbod jeugd en gezin",
        "publisher": "Sociaal Domein Almere / Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://sociaaldomein.almere.nl/preventie-voor-jeugd-en-gezin/aanbod-jeugd-en-gezin",
        "status": "current",
        "priority_rank": 64,
        "selected_source_file": "sources/82-sociaal-domein-aanbod-jeugd-gezin.html",
    },
    {
        "source_number": 83,
        "document_id": "mun_almere_sociale_veerkracht_almeerders",
        "title": "Sociale veerkracht van Almeerders",
        "short_title": "Sociale veerkracht van Almeerders",
        "publisher": "Gemeente Almere / Movisie / Platform31 / Verwey-Jonker Instituut",
        "publication_date": "2023-11-01",
        "document_type": "research_report",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/sociale-staat-van-almere/sociale-veerkracht-van-almeerders",
        "status": "current",
        "priority_rank": 65,
        "selected_source_file": "sources/83-sociale-veerkracht-van-almeerders.html",
    },
    {
        "source_number": 84,
        "document_id": "mun_deschoor_buurtkamers",
        "title": "Buurtkamers",
        "short_title": "De Schoor buurtkamers",
        "publisher": "De Schoor",
        "publication_date": None,
        "document_type": "provider_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.deschoor.nl/buurtkamers",
        "status": "current",
        "priority_rank": 66,
        "selected_source_file": "sources/84-deschoor-buurtkamers.html",
    },
    {
        "source_number": 85,
        "document_id": "mun_deschoor_initiatievenbureau",
        "title": "Initiatievenbureau",
        "short_title": "De Schoor Initiatievenbureau",
        "publisher": "De Schoor",
        "publication_date": None,
        "document_type": "provider_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.deschoor.nl/initiatievenbureau",
        "status": "current",
        "priority_rank": 67,
        "selected_source_file": "sources/85-deschoor-initiatievenbureau.html",
    },
    {
        "source_number": 86,
        "document_id": "mun_deschoor_buurtkracht",
        "title": "Buurtkracht",
        "short_title": "De Schoor Buurtkracht",
        "publisher": "De Schoor",
        "publication_date": None,
        "document_type": "provider_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.deschoor.nl/buurtkracht",
        "status": "current",
        "priority_rank": 68,
        "selected_source_file": "sources/86-deschoor-buurtkracht.html",
    },
    {
        "source_number": 87,
        "document_id": "mun_deschoor_opbouwwerk_almere",
        "title": "Opbouwwerk in Almere",
        "short_title": "De Schoor opbouwwerk Almere",
        "publisher": "De Schoor",
        "publication_date": None,
        "document_type": "provider_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.deschoor.nl/opbouwwerkalmere",
        "status": "current",
        "priority_rank": 69,
        "selected_source_file": "sources/87-deschoor-opbouwwerk-almere.html",
    },
    {
        "source_number": 88,
        "document_id": "mun_vmca_meerjarenvisie_2022_2025",
        "title": "Meerjarenvisie 2022-2025",
        "short_title": "VMCA Meerjarenvisie 2022-2025",
        "publisher": "Vrijwilligers en Mantelzorg Centrale Almere",
        "publication_date": "2022-01-01",
        "document_type": "provider_policy_plan",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.vmca.nl/uploads/content/file/www.vmca.nl/meerjarenvisie-vmca-2022-2025.pdf",
        "status": "current",
        "priority_rank": 70,
        "selected_source_file": "sources/88-vmca-meerjarenvisie-2022-2025.pdf",
    },
    {
        "source_number": 89,
        "document_id": "mun_humanitas_almere",
        "title": "Humanitas Almere",
        "short_title": "Humanitas Almere",
        "publisher": "Humanitas",
        "publication_date": None,
        "document_type": "provider_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.humanitas.nl/afdeling/almere/",
        "status": "current",
        "priority_rank": 71,
        "selected_source_file": "sources/89-humanitas-almere.html",
    },
    {
        "source_number": 90,
        "document_id": "mun_almere_almeers_preventieakkoord",
        "title": "Almeers Preventieakkoord",
        "short_title": "Almeers Preventieakkoord",
        "publisher": "Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/zorg-en-welzijn/almeers-preventieakkoord",
        "status": "current",
        "priority_rank": 72,
        "selected_source_file": "sources/90-almeers-preventieakkoord.html",
    },
    {
        "source_number": 91,
        "document_id": "mun_almere_wijkteams_ontmoeting",
        "title": "Ontmoeting",
        "short_title": "Wijkteams Almere Ontmoeting",
        "publisher": "Wijkteams Almere / Gemeente Almere",
        "publication_date": None,
        "document_type": "municipal_service_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://wijkteams.almere.nl/ontmoeting",
        "status": "current",
        "priority_rank": 73,
        "selected_source_file": "sources/91-wijkteams-ontmoeting.html",
    },
    {
        "source_number": 92,
        "document_id": "reg_ggd_flevoland_kadernota_2025",
        "title": "Kadernota GGD Flevoland 2025",
        "short_title": "GGD kadernota 2025",
        "publisher": "GGD Flevoland",
        "publication_date": "2024-03-29",
        "document_type": "regional_budget_framework",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ggdflevoland.nl/app/uploads/sites/6/2024/04/3.2-Kadernota-kern-GGD-2025-v-29mrt2024-gg10042024_.pdf",
        "status": "historical",
        "priority_rank": 74,
        "selected_source_file": "sources/92-ggd-flevoland-kadernota-2025.pdf",
    },
    {
        "source_number": 93,
        "document_id": "reg_flever_zorgzaam_flevoland_project",
        "title": "Zorgzaam Flevoland",
        "short_title": "Flever Zorgzaam Flevoland",
        "publisher": "Flever",
        "publication_date": None,
        "document_type": "regional_project_page",
        "jurisdiction_level": "regional",
        "source_url": "https://flever.nl/project/zorgzaam-flevoland/",
        "status": "current",
        "priority_rank": 75,
        "selected_source_file": "sources/93-flever-zorgzaam-flevoland.html",
    },
    {
        "source_number": 94,
        "document_id": "reg_flever_meerjarenplan_2025_2028",
        "title": "Meerjarenplan Flever 2025-2028",
        "short_title": "Flever meerjarenplan",
        "publisher": "Flever",
        "publication_date": "2025-04-07",
        "document_type": "provider_policy_plan",
        "jurisdiction_level": "regional",
        "source_url": "https://flever.nl/wp-content/uploads/2025/04/Meerjarenplan-Flever-JvG5-DEF.pdf",
        "status": "current",
        "priority_rank": 76,
        "selected_source_file": "sources/94-flever-meerjarenplan-2025-2028.pdf",
    },
    {
        "source_number": 95,
        "document_id": "reg_flever_inwoners_onderdeel_pga",
        "title": "Inwoners onderdeel van Positief Gezond Almere (PGA)",
        "short_title": "Flever inwoners PGA",
        "publisher": "Flever",
        "publication_date": "2025-12-08",
        "document_type": "provider_news_page",
        "jurisdiction_level": "regional",
        "source_url": "https://flever.nl/sterk-met-inwoners/",
        "status": "current",
        "priority_rank": 77,
        "selected_source_file": "sources/95-flever-inwoners-onderdeel-pga.html",
    },
    {
        "source_number": 96,
        "document_id": "reg_almere_zorglandschap_wmo",
        "title": "Zorglandschap Wmo",
        "short_title": "Zorglandschap Wmo",
        "publisher": "Regio Almere / Gemeente Almere",
        "publication_date": None,
        "document_type": "regional_project_page",
        "jurisdiction_level": "regional",
        "source_url": "https://regio.almere.nl/zorglandschap-wmo",
        "status": "current",
        "priority_rank": 78,
        "selected_source_file": "sources/96-regio-almere-zorglandschap-wmo.html",
    },
    {
        "source_number": 97,
        "document_id": "reg_zorglandschap_wmo_uitvoeringsprogramma_2022",
        "title": "Voortgang uitvoeringsprogramma Zorglandschap Wmo Flevoland",
        "short_title": "Uitvoeringsprogramma Zorglandschap Wmo",
        "publisher": "Sociaal Domein Flevoland",
        "publication_date": "2022-02-01",
        "document_type": "regional_project_plan",
        "jurisdiction_level": "regional",
        "source_url": "https://sociaaldomeinflevoland.nl/sites/default/files/documents/Uitvoeringsprogramma%20Zorglandschap%20Wmo%20%282%29.pdf",
        "status": "historical",
        "priority_rank": 79,
        "selected_source_file": "sources/97-uitvoeringsprogramma-zorglandschap-wmo-flevoland-2022.pdf",
    },
    {
        "source_number": 98,
        "document_id": "reg_zorglandschap_wmo_monitor_2025",
        "title": "Monitor Zorglandschap Wmo 2025",
        "short_title": "Monitor Zorglandschap 2025",
        "publisher": "Regio Flevoland / Gemeente Lelystad",
        "publication_date": "2025-01-01",
        "document_type": "regional_report",
        "jurisdiction_level": "regional",
        "source_url": "https://lelystad.bestuurlijkeinformatie.nl/Document/View/e42037b5-60d3-43bf-b89a-1c3f36028809",
        "status": "current",
        "priority_rank": 80,
        "selected_source_file": "sources/98-monitor-zorglandschap-wmo-2025.pdf",
    },
    {
        "source_number": 99,
        "document_id": "reg_zonmw_samen_sterker_uitvoeringsplan",
        "title": "Uitvoeringsplan: Samen Sterker in de Wijk in Flevoland",
        "short_title": "ZonMw uitvoeringsplan SSidW",
        "publisher": "ZonMw",
        "publication_date": "2022-01-01",
        "document_type": "national_project_overview",
        "jurisdiction_level": "national",
        "source_url": "https://projecten.zonmw.nl/nl/project/uitvoeringsplan-samen-sterker-de-wijk-flevolandmentale-veerkracht-de-wijk",
        "status": "historical",
        "priority_rank": 81,
        "selected_source_file": "sources/99-zonmw-uitvoeringsplan-samen-sterker-flevoland.html",
    },
    {
        "source_number": 100,
        "document_id": "reg_zonmw_samen_sterker_startsubsidie",
        "title": "Samen sterker in de wijk",
        "short_title": "ZonMw SSidW startsubsidie",
        "publisher": "ZonMw",
        "publication_date": "2020-01-01",
        "document_type": "national_project_overview",
        "jurisdiction_level": "national",
        "source_url": "https://projecten.zonmw.nl/nl/project/samen-sterker-de-wijk",
        "status": "historical",
        "priority_rank": 82,
        "selected_source_file": "sources/100-zonmw-samen-sterker-de-wijk.html",
    },
    {
        "source_number": 101,
        "document_id": "mun_almere_pga_samen_sterker_wijk",
        "title": "Samen Sterker in de Wijk: mentale veerkracht in Almere",
        "short_title": "PGA Samen Sterker in de Wijk",
        "publisher": "Positief Gezond Almere",
        "publication_date": None,
        "document_type": "municipal_program_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://positiefgezondalmere.nl/projecten/samen-sterker-in-de-wijk/",
        "status": "current",
        "priority_rank": 83,
        "selected_source_file": "sources/101-pga-samen-sterker-in-de-wijk.html",
    },
    {
        "source_number": 102,
        "document_id": "mun_almere_subsidieregister_2023",
        "title": "Subsidieregister 2023",
        "short_title": "Subsidieregister 2023",
        "publisher": "Gemeente Almere",
        "publication_date": "2023-01-01",
        "document_type": "municipal_info_page",
        "jurisdiction_level": "municipal",
        "source_url": "https://www.almere.nl/subsidies/subsidieregister/subsidieregister-2023",
        "status": "current",
        "priority_rank": 84,
        "selected_source_file": "sources/102-almere-subsidieregister-2023.html",
    },
    {
        "source_number": 103,
        "document_id": "mun_almere_evaluatie_schakelteams_2021",
        "title": "Evaluatie schakelteams",
        "short_title": "Evaluatie schakelteams",
        "publisher": "Gemeente Almere Onderzoek & Statistiek",
        "publication_date": "2021-11-01",
        "document_type": "research_report",
        "jurisdiction_level": "municipal",
        "source_url": "https://oens.almere.nl/fileadmin/files/sites/OenS/2022/Evaluatie_schakelteams.pdf",
        "status": "historical",
        "priority_rank": 85,
        "selected_source_file": "sources/103-evaluatie-schakelteams.pdf",
    },
    {
        "source_number": 104,
        "document_id": "reg_samen_sterker_in_de_wijk_home",
        "title": "Samen Sterker in de Wijk",
        "short_title": "Samen Sterker in de Wijk",
        "publisher": "Samen Sterker in de Wijk",
        "publication_date": None,
        "document_type": "regional_project_page",
        "jurisdiction_level": "regional",
        "source_url": "https://www.ssidw.nl/",
        "status": "current",
        "priority_rank": 86,
        "selected_source_file": "sources/104-samen-sterker-in-de-wijk-home.html",
    },
]


TRACKED_EMPTY_DIRECTORIES = [
    "config",
    "prompts",
    "tests",
    "docs",
    "data/intermediate/text",
    "data/intermediate/chunks",
    "data/intermediate/tables",
    "data/extracted/documents",
    "data/extracted/claims",
    "data/extracted/municipal",
    "data/schemas",
    "data/logs",
]


def write_gitkeep(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    gitkeep = directory / ".gitkeep"
    gitkeep.write_text("", encoding="utf-8")


def manifest_entry_for_document(doc: dict, level_dirs: dict[str, Path]) -> dict:
    source_path = REPO_ROOT / doc["selected_source_file"]
    if not source_path.exists():
        raise FileNotFoundError(f"Missing source file: {source_path}")

    ext = source_path.suffix.lower()
    destination_dir = level_dirs[doc["jurisdiction_level"]]
    destination_path = destination_dir / f"{doc['document_id']}{ext}"
    copy2(source_path, destination_path)

    return {
        "document_id": doc["document_id"],
        "title": doc["title"],
        "short_title": doc["short_title"],
        "publisher": doc["publisher"],
        "publication_date": doc["publication_date"],
        "document_type": doc["document_type"],
        "jurisdiction_level": doc["jurisdiction_level"],
        "file_path": destination_path.relative_to(REPO_ROOT).as_posix(),
        "source_url": doc["source_url"],
        "status": doc["status"],
        "priority_rank": doc["priority_rank"],
        "source_number": doc["source_number"],
        "selected_source_file": doc["selected_source_file"],
    }


def load_preserved_manifest_entries(manifest_path: Path, managed_document_ids: set[str]) -> list[dict]:
    if not manifest_path.exists():
        return []

    entries = json.loads(manifest_path.read_text(encoding="utf-8"))
    preserved = []
    for entry in entries:
        if entry["document_id"] in managed_document_ids:
            continue
        raw_path = REPO_ROOT / entry["file_path"]
        if not raw_path.exists():
            raise FileNotFoundError(f"Existing manifest entry points to missing raw file: {raw_path}")
        preserved.append(entry)
    return preserved


def main() -> None:
    raw_root = REPO_ROOT / "data" / "raw"
    level_dirs = {
        "national": raw_root / "national",
        "regional": raw_root / "regional",
        "municipal": raw_root / "municipal",
    }

    for directory in level_dirs.values():
        directory.mkdir(parents=True, exist_ok=True)

    for relative_dir in TRACKED_EMPTY_DIRECTORIES:
        write_gitkeep(REPO_ROOT / relative_dir)

    manifest_path = raw_root / "manifest.json"
    managed_document_ids = {doc["document_id"] for doc in DOCUMENTS}
    manifest_entries = load_preserved_manifest_entries(manifest_path, managed_document_ids)
    manifest_entries.extend(manifest_entry_for_document(doc, level_dirs) for doc in DOCUMENTS)

    manifest_entries.sort(key=lambda item: item["priority_rank"])
    manifest_path.write_text(
        json.dumps(manifest_entries, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    print(f"Wrote {manifest_path.relative_to(REPO_ROOT).as_posix()}")
    print(f"Prepared {len(manifest_entries)} Phase 0 source documents")


if __name__ == "__main__":
    main()
